name: Tests

on: [push, pull_request]

jobs:
  quickrun:
    runs-on: ubuntu-latest

    steps:
      - name: ACTION CHECKOUT
        uses: actions/checkout@v2
      - name: SETUP PYTHON VERSION
        uses: actions/setup-python@v2
      - name: INSTALL DEPENDENCIES
        run: python -m pip install -r requirements.txt
      - name: TEST
        run: python -m pytest tests


